CREATE DATABASE IF NOT EXISTS boarding_house CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE boarding_house;

CREATE TABLE rooms (id INT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, rent DECIMAL(12,2) NOT NULL, area DECIMAL(8,2), max_occupants INT NOT NULL DEFAULT 1, status ENUM('vacant','occupied','maintenance') NOT NULL DEFAULT 'vacant', notes TEXT);
CREATE TABLE tenants (id INT AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(120) NOT NULL, phone VARCHAR(20), cccd VARCHAR(30) UNIQUE, birth_date DATE, gender VARCHAR(15), permanent_address TEXT, move_in_date DATE, room_id INT NULL, deposit DECIMAL(12,2) NOT NULL DEFAULT 0, notes TEXT, id_front VARCHAR(255), id_back VARCHAR(255), contract_file VARCHAR(255), FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE SET NULL);
CREATE TABLE users (id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(80) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, full_name VARCHAR(120) NOT NULL, role ENUM('admin','tenant') NOT NULL DEFAULT 'tenant', tenant_id INT NULL, FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE);
CREATE TABLE utility_readings (id INT AUTO_INCREMENT PRIMARY KEY, room_id INT NOT NULL, reading_month DATE NOT NULL, old_electricity DECIMAL(12,2) NOT NULL, new_electricity DECIMAL(12,2) NOT NULL, electricity_rate DECIMAL(12,2) NOT NULL, old_water DECIMAL(12,2) NOT NULL, new_water DECIMAL(12,2) NOT NULL, water_rate DECIMAL(12,2) NOT NULL, UNIQUE KEY uniq_room_month (room_id, reading_month), FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE);
CREATE TABLE services (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, unit_price DECIMAL(12,2) NOT NULL, calculation ENUM('room','person') NOT NULL DEFAULT 'room', is_active BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE room_services (room_id INT NOT NULL, service_id INT NOT NULL, PRIMARY KEY (room_id,service_id), FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE, FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE CASCADE);
CREATE TABLE invoices (id INT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(40) NOT NULL UNIQUE, room_id INT NOT NULL, tenant_id INT NULL, invoice_month DATE NOT NULL, room_fee DECIMAL(12,2) NOT NULL DEFAULT 0, electricity_fee DECIMAL(12,2) NOT NULL DEFAULT 0, water_fee DECIMAL(12,2) NOT NULL DEFAULT 0, service_fee DECIMAL(12,2) NOT NULL DEFAULT 0, extra_fee DECIMAL(12,2) NOT NULL DEFAULT 0, discount DECIMAL(12,2) NOT NULL DEFAULT 0, total DECIMAL(12,2) NOT NULL DEFAULT 0, due_date DATE, status ENUM('unpaid','partial','paid') NOT NULL DEFAULT 'unpaid', notes TEXT, UNIQUE KEY uniq_invoice_room_month (room_id,invoice_month), FOREIGN KEY (room_id) REFERENCES rooms(id), FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL);
CREATE TABLE invoice_details (id INT AUTO_INCREMENT PRIMARY KEY, invoice_id INT NOT NULL, description VARCHAR(255) NOT NULL, amount DECIMAL(12,2) NOT NULL, FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE);
CREATE TABLE payments (id INT AUTO_INCREMENT PRIMARY KEY, invoice_id INT NOT NULL, amount DECIMAL(12,2) NOT NULL, paid_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, method VARCHAR(50) DEFAULT 'Tien mat', notes TEXT, FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE);
CREATE TABLE payment_requests (id INT AUTO_INCREMENT PRIMARY KEY, invoice_id INT NOT NULL, requester_id INT NULL, amount DECIMAL(12,2) NOT NULL, method VARCHAR(50) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', requested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, processed_at DATETIME NULL, FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE, FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE SET NULL);
